# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample-project' do

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxFlow'
  pod 'ReactorKit'


  target 'Sample-projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
